name: build-main
run-name: build-main
on:
  push:
    branches:
      - main
  schedule:
    # every 15 minutes
    - cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: main
    steps:
      - uses: actions/checkout@v3

      - run: sh ./download.sh

      - run: ls ./files

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
